name: GitHub Actions Demo
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Display Trigger Event
        run: |
          echo "Event name ${{ github.event_name }}"

      - name: Display Branch Name
        run: |
          echo "Branch name ${{ github.ref }}"

      - name: List Repository Files
        run: |
          echo "List of repository files ${{ github.repository }}"
          tree
    
    
